### ISSUE TITLE
Email Field does not send emails to the emails in the BCC

### ISSUE THREAD

**Issue by ricoo123** [Octopoos/SEBLOD#201]
Hi,

Email Field does not send emails to the emails in the BCC.

See photo please.

Thank you
![3](https://cloud.githubusercontent.com/assets/12091716/15398303/c6586fb2-1deb-11e6-9ba3-06810a23a0ac.png)

**Comment by sebastienheraud** [comment]
Hi rico,
This issue appear when CC and BCC are enable but without any valid email (or an empty string)
The following commit should fix it https://github.com/Octopoos/SEBLOD/commit/ba0baad3857d604674077a082b48f5a2e02c3f0f, please have a try and confirm.
Regards,
Saba.

**Comment by ricoo123** [comment]
Hi Seb,

Unfortunately it's still not working.

Regards,
rico

**Comment by ricoo123** [comment]
Hi Seb,

This problem is very annoying and I will open a new issue if you don't take care of it.

Everyone to whom the SEBLOD Email Filed is sending emails is knowing that my site is sending double emails.

I think this is intolerable.

Regards,
rico

**Comment by klas** [comment]
Hi rico123, please clarify what the actual issue is, in the issue you wrote  that emails to the field in BCC are not sent, but now you are saying that people are getting double emails? This two things are directly opposite.

**Comment by ricoo123** [comment]
Hi Klas,

Currently to get a copy of the email I select the admin user name in the To(Administrators) field. In this way the receiver can see that the email is sent to his email and to the admin email.

The purpose of the BCC field is to get a copy of the email without the user to know, but this is not the case with the BCC in the SEBLOD email field.

If I unselect the admin in the To(Administrators) field and write an email in the BCC field then I don't get a copy of the email at all and if I select it then the user sees that email is sent to 2 emails.

Regards

**Comment by klas** [comment]
I jsut tested and set Bcc to "E-mail" and entered some email, and emial got sent to this address correctly without being visible to the recipient. Not sure what would be an issue here, everyhitng works as it should?

 What you need to remember is that **To can't be empty**, you need to put something there, in your case I would suggest you just use this field to send a copy to the sender.

**Comment by klas** [comment]
On second thought - "To can't be empty" is actually a bug as Joomla allows just cc or bcc (in my test there was no error but email is not sent either)

**Comment by ricoo123** [comment]
So the problem is that if we enter field name in the To(Fields) and select an admin in the To(Administrators) field the email gets sent to both but the receiver sees to whom the email is sent. Then if we enter field name in the To(Fields) and enter email address in the BCC the email is not being sent.

The question is how to get the email sent without the user to see that the email is also sent to the admin? Currently this is not possible.

**Comment by sebastienlapoux** [comment]
Just used 2 email fields...

**Comment by ricoo123** [comment]
I already have 2, one for New and one for Edit, so they will become 4. That's a work around somehow but problem remains. Thanks
