### ISSUE TITLE
[install error] Duplicate column name 'path' installing plg_content_cck.zip

### ISSUE THREAD

**Issue by raramuridesign** [Octopoos/SEBLOD#698]
@sebastienheraud 
Upgrading to Seblod 3.23.2 this plugin plg_content_cck.zip
Throws this error.

Can you please let us know what or how to solve this
Thanks
M.

**Comment by raramuridesign** [comment]
@sebastienheraud There is also a different error when installing the entire package, the errors are really no use to anyone, so there is no way to start troubleshooting this.

Error when installing entire package is

```
Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
Package Update: There was an error installing an extension: plg_content_cck.zip

```

Could you let me know where to start with this? or how to get further information to sort this out?
Thanks
M

**Comment by sebastienheraud** [comment]
Hi @raramuridesign,
The 1st issue is fixed with the latest packages.

For the 2nd this is a standard MySQL error output, you'll find many topics on the web about it.
It means that you have too many columns on a table, and that a query is trying to add more or alter one that you'll take more space and so it is not allowed. One trick is to change the Data Type of some VARCHAR columns to TEXT, as TEXT columns are stored separately (and so not added to the size limit).
I don't know which query/table it is here, so have a look at your database structure, and you may find the one where you added to many columns. (maybe `cck_store_item_users` is a good start)

Saba.

**Comment by raramuridesign** [comment]
@sebastienheraud I finally had time to look at this.
Seems I am still getting the same error for the path issue in the latest version of the zip file
plg_content_cck.zip

Is it possible you can take a look and see what is going on.
The other issue does not seem to be an problem any more.

![image](https://github.com/Octopoos/SEBLOD/assets/902376/d1cc9def-2b7a-4c98-ba38-b4212d69df72)

M
